# Generated by Django 2.1.3 on 2018-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelf', '0002_auto_20181119_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
